import type { Metadata } from "next";
import "./globals.css";
import { Manrope, Marcellus } from 'next/font/google'

const manrope = Manrope({
  weight: ['200','300','400','700', '800'],
  subsets: ['latin'],
  variable: '--font-manrope',
})

export const marcellus = Marcellus({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-marcellus',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={`${manrope.className} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}