import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google'
import localFont from 'next/font/local'

const nunito = Nunito({
  weight: ['200','300','400','700'],
  subsets: ['latin'],
  variable: '--font-lato',
})

export const daniel = localFont({
  src: "../../public/font/Daniel-Bold.otf"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html 
      lang="en"
      className={`${nunito.className} antialiased`}>
      <body>
        {children}
      </body>
    </html>
  );
}